FROM nvidia/cuda:12.6.3-cudnn-runtime-ubuntu24.04

ARG FACEFUSION_VERSION=v3.1.0.nsfw
ENV GRADIO_SERVER_NAME=0.0.0.0
ENV PIP_BREAK_SYSTEM_PACKAGES=1
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python3.12/dist-packages/tensorrt_libs

WORKDIR /facefusion

RUN apt-get update
RUN apt-get install python3.12 -y
RUN apt-get install python-is-python3 -y
RUN apt-get install pip -y
RUN apt-get install git -y
RUN apt-get install curl -y
RUN apt-get install ffmpeg -y
RUN pip install tensorrt==10.6.0 --extra-index-url https://pypi.nvidia.com

RUN git clone https://github.com/xiongyumail/facefusion.git --branch ${FACEFUSION_VERSION} --single-branch .
RUN python install.py --onnxruntime cuda --skip-conda

# Install ffmpeg6 to solve ubuntu22.04 ffmpeg4 image error problem
RUN apt-get install software-properties-common -y
RUN add-apt-repository ppa:ubuntuhandbook1/ffmpeg6 -y
RUN apt-get install ffmpeg -y
