services:
 facefusion-openvino:
  build:
   context: .
   dockerfile: Dockerfile.openvino
  command: [ 'python', 'facefusion.py', 'run', '--execution-providers', 'openvino' ]
  volumes:
  - .assets:/facefusion/.assets
  - .caches:/facefusion/.caches
  - .jobs:/facefusion/.jobs
  - /usr/lib/wsl:/usr/lib/wsl
  devices:
  - /dev/dxg:/dev/dxg
