name: ci

on: [ push, pull_request ]

jobs:
 test:
  name: ${{ matrix.config.image-name }}
  runs-on: ubuntu-latest
  strategy:
   matrix:
    config:
    - { docker-file: 'Dockerfile.cpu', image-name: 'facefusion-cpu' }
    - { docker-file: 'Dockerfile.cuda', image-name: 'facefusion-cuda' }
    - { docker-file: 'Dockerfile.tensorrt', image-name: 'facefusion-tensorrt' }
    - { docker-file: 'Dockerfile.rocm', image-name: 'facefusion-rocm' }
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Build
    run: docker build -f ${{ matrix.config.docker-file }} -t ${{ matrix.config.image-name }} .
  - name: Run
    run: docker run -d ${{ matrix.config.image-name }}
  - name: Validate
    run: docker ps | grep -q ${{ matrix.config.image-name }}
